-- 002 B 账号矩阵（阶段1 第一步）
CREATE TABLE IF NOT EXISTS ops_accounts (
  id                   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id            VARCHAR(36)     NOT NULL,
  platform             VARCHAR(32)     NOT NULL,
  platform_account_id  VARCHAR(128)    NOT NULL,
  nickname             VARCHAR(128)    NULL,
  avatar_url           VARCHAR(512)    NULL,
  identity             VARCHAR(32)     NOT NULL DEFAULT 'matrix',
  track                VARCHAR(64)     NULL,
  stage                VARCHAR(32)     NOT NULL DEFAULT 'nurturing',
  status               VARCHAR(32)     NOT NULL DEFAULT 'unsigned',
  token_enc            TEXT            NULL COMMENT 'AES-256-GCM 加密的 access_token',
  platform_open_id     VARCHAR(128)    NULL COMMENT 'OAuth open_id（发布必传）',
  refresh_token_enc    TEXT            NULL COMMENT 'AES-256-GCM 加密的 refresh_token',
  token_expire_at      DATETIME        NULL,
  last_sync_at         DATETIME        NULL,
  last_active_at       DATETIME        NULL,
  fans_count           INT             NOT NULL DEFAULT 0,
  follow_count         INT             NOT NULL DEFAULT 0,
  like_count           INT             NOT NULL DEFAULT 0,
  remark               VARCHAR(255)    NULL,
  created_at           DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at           DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at           DATETIME(6)     NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_account_platform (tenant_id, platform, platform_account_id),
  KEY idx_account_tenant (tenant_id),
  KEY idx_account_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='账号矩阵';
