-- 005 E 选题 + F 脚本（阶段1 第四五步）
CREATE TABLE IF NOT EXISTS ops_topics (
  id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id       VARCHAR(36)     NOT NULL,
  analysis_id     BIGINT          NULL COMMENT 'D 分析任务 id',
  attribution_id  VARCHAR(128)    NOT NULL,
  title           VARCHAR(255)    NOT NULL,
  human_driver    VARCHAR(16)     NOT NULL COMMENT '7 人性',
  emotion         VARCHAR(16)     NOT NULL COMMENT '6 情绪',
  formula_tags    JSON            NULL,
  status          VARCHAR(16)     NOT NULL DEFAULT 'idea',
  score           INT             NOT NULL DEFAULT 0,
  ab_variant_of   BIGINT          NULL,
  scheduled_at    DATETIME        NULL,
  account_id      BIGINT          NULL,
  prompt_version  VARCHAR(32)     NOT NULL DEFAULT 'v1',
  model_used      VARCHAR(64)     NOT NULL DEFAULT '',
  created_at      DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at      DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at      DATETIME(6)     NULL,
  PRIMARY KEY (id),
  KEY idx_topic_tenant (tenant_id),
  KEY idx_topic_attribution (tenant_id, attribution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='选题库';

CREATE TABLE IF NOT EXISTS ops_scripts (
  id                BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  tenant_id         VARCHAR(36)     NOT NULL,
  topic_id          INT             NOT NULL,
  attribution_id    VARCHAR(64)     NOT NULL,
  title             VARCHAR(255)    NOT NULL,
  content           TEXT            NOT NULL,
  hook              TEXT            NOT NULL,
  hook_emotion      VARCHAR(32)     NOT NULL,
  spoken_track      JSON            NULL COMMENT '口播时序',
  subtitle_track    JSON            NULL COMMENT '字幕时序',
  template_id       VARCHAR(32)     NULL,
  version           INT             NOT NULL DEFAULT 1,
  parent_version_id INT             NULL,
  status            VARCHAR(32)     NOT NULL DEFAULT 'draft',
  compliance_risk   JSON            NULL,
  prompt_version    VARCHAR(32)     NOT NULL,
  model_used        VARCHAR(64)     NULL,
  created_at        DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at        DATETIME(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  deleted_at        DATETIME(6)     NULL,
  PRIMARY KEY (id),
  KEY idx_script_tenant (tenant_id),
  KEY idx_script_topic (tenant_id, topic_id),
  KEY idx_script_attribution (tenant_id, attribution_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='脚本库';
